# Generated by Django 3.2 on 2021-04-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteToPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_name', models.CharField(max_length=20)),
                ('voting_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_votes_for_win', models.IntegerField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('winner', models.CharField(max_length=20)),
                ('vote_to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votetoperson')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('photo', models.TextField()),
                ('age', models.IntegerField()),
                ('short_biography', models.TextField()),
                ('vote_to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votetoperson')),
            ],
        ),
    ]
