# Generated by Django 3.2 on 2021-04-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='vote_to_person',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_to_person',
        ),
        migrations.AddField(
            model_name='vote',
            name='person',
            field=models.ManyToManyField(through='voting.VoteToPerson', to='voting.Person'),
        ),
        migrations.AddField(
            model_name='votetoperson',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='voting.person'),
        ),
        migrations.AddField(
            model_name='votetoperson',
            name='vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='voting.vote'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.TextField(default='D:\\Programming\\web-app\\voting_app\\mysite\\voting\\static\\voting\\IMG'),
        ),
    ]
