# Generated by Django 3.2 on 2021-04-10 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210409_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.TextField(default='mysite\\voting\\static\\voting\\IMG'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 4, 15)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 4, 10)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='winner',
            field=models.CharField(default='Победитель пока не определен.', max_length=40),
        ),
    ]
