# Generated by Django 3.2 on 2021-04-12 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210412_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 22, 6, 13, 351340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 12, 22, 6, 13, 351340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='winner',
            field=models.CharField(default='Победитель пока не определен. Голосование продолжается.', max_length=60),
        ),
        migrations.AlterField(
            model_name='votetoperson',
            name='vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vote_to_person', to='voting.vote'),
        ),
    ]
